sonar.projectKey=cyberfinrisk-backend
sonar.projectName=CyberFinRisk Backend
sonar.projectVersion=3.0.0

sonar.host.url=http://localhost:9000
sonar.token=sqp_placeholder_change_me

sonar.sourceEncoding=UTF-8
sonar.language=py
sonar.sources=.
sonar.exclusions=\
  **/__pycache__/**,\
  **/knowledge_base/**,\
  **/Doc/**,\
  **/.env*,\
  **/venv/**,\
  **/data/**, \
  **/static/**, \
  **/frontend/**

sonar.python.coverage.reportPaths=coverage.xml
sonar.python.xunit.reportPath=junit.xml
